version: "3"
services:
  db:
    image: postgres:15.3
    user: "root:root"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - "./db-data:/var/lib/postgresql/data"